version: '2'
 
services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    volumes:
      - ./web/:/home/django/app
    command: gunicorn --bind 0.0.0.0:8000 server:app
    depends_on:
      - postgres
    environment:
      - FLASK_APP=server.py
      - FLASK_DEBUG=1
 
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    depends_on:
      - web
 
  data:
    image: postgres:9.6
    volumes:
      - /var/lib/postgresql
    command: "true"
 
  postgres:
    restart: always
    build: ./postgresql
    volumes_from:
      - data
    expose:
      - "5432"
    ports:
      - "5432:5432"
