version: '2'
 
services:
  # web:
  #   restart: always
  #   build: ./web
  #   expose:
  #     - "8000"
  #   volumes:
  #     - .:/home/django
  #   working_dir: /home/django
  #   command: bash -c "cd /home/django && gunicorn --bind 0.0.0.0:8000 server:app"
  #   depends_on:
  #     - postgres
  #   environment:
  #     - FLASK_APP=server.py
  #     - FLASK_DEBUG=1
  #   networks:
  #     - frontend
  #     - backend
  web:
    build: ./web
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - frontend
      - backend
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    depends_on:
      - web
    networks:
      - frontend
 
  data:
    image: postgres:9.6
    volumes:
      - /var/lib/postgresql
    command: "true"
 
  postgres:
    restart: always
    build: ./postgresql
    volumes_from:
      - data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  frontend:
  backend:
