FROM nginx:1.11.3
COPY django.conf /etc/nginx/conf.d/default.conf

#RUN ls -la /etc/nginx/
#RUN ls -la /etc/nginx/conf.d
#RUN cat /etc/nginx/conf.d/default.conf
#RUN ln -s /etc/nginx/sites-available/django.conf /etc/nginx/sites-enabled/django.conf

# RUN rm /etc/nginx/nginx.conf
# RUN rm /etc/nginx/conf.d/default.conf
# COPY family_recipes.conf /etc/nginx/conf.d/